services:
  client-builder:
    container_name: client-builder
    build:
      dockerfile: Dockerfile
    environment:
      - CROSS_DOCKER_IN_DOCKER=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/usr/src/proj