services:
  service:
    container_name: server
    build:
      context: ..
      dockerfile: ./server/Dockerfile
    ports:
      - 7878:7878
    volumes:
      - ./data:/the_book/data
    environment:
      - PORT=7878
    restart: always