services:
  the_book_server:
    container_name: the_book_server
    build:
      context: ..
      dockerfile: ./server/Dockerfile
    ports:
      - 7878:7878
    volumes:
      - ./data:/the_book/server/data
      - ./sessions:/the_book/server/sessions
      - ./saves:/the_book/server/saves
    environment:
      - PORT=7878
      - DB_NAME=${DB_NAME}
      - DB_HOST=the_book_db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASS}@the_book_db:3306/${DB_NAME}
    restart: always
    depends_on:
      - the_book_db
  the_book_db:
    container_name: the_book_db
    image: mysql:8
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always
